### ISSUE TITLE
Movie details page in Movie List is not shown properly

### ISSUE THREAD

**Issue by dml33** [mregni/statistics-for-emby-server-CORE#1]
Hi.

I am using your plugin 2.0.6.0 version with Emby Server 3.6.0.61 version.

When I go to movie list and click on a movie, the new page is not rendered properly. It is full of labels, such as in the following image:

![image](https://user-images.githubusercontent.com/25033130/48314247-37125100-e5c7-11e8-85dc-398ec2dda9d8.png)

Could you please fix it? I find quite useful your plugin in order to be aware of what I actually have in the server.

Thanks!!

**Comment by mregni** [comment]
Hi, sorry for the very late response.

At the moment I'm not updating the plugin. This error seems some CSS problems, did you try refreshing the page or clearing your cache?

The reason why I'm no longer updating the plugin is that I'm building EmbyStat => https://github.com/mregni/EmbyStat. It's a standalone server that will (in time) do a lot more than the plugin itself.
